// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Cấu hình Prisma CLI cho "Luyện Thi 2027".
// Tài liệu: https://www.prisma.io/docs/orm/reference/prisma-config-reference
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
